/**
 * Test data for prefilling the form — used by admin users for testing.
 * Uses "Adrian Staněk" / "janko@stanektech.cz" as the primary contact.
 */
export const getTestFormData = () => ({
  // Krok 1 — Identifikační údaje zákazníka
  companyName: 'StanekTech s.r.o.',
  ico: '12345678',
  dic: 'CZ12345678',
  contactPerson: 'Adrian Staněk',
  phone: '+420 777 123 456',
  email: 'janko@stanektech.cz',
  companyAddress: 'Vinohradská 42, 120 00 Praha 2',
  address: 'Vinohradská 42, 120 00 Praha 2',
  sameAsCompanyAddress: true,
  customerType: {
    industrial: true,
    commercial: false,
    services: false,
    agriculture: false,
    public: false,
    other: false,
    otherSpecification: '',
  },
  additionalContacts: [
    {
      id: '1',
      name: 'Jan Novák',
      position: 'Technický ředitel',
      phone: '+420 602 345 678',
      email: 'novak@stanektech.cz',
      isPrimary: false,
    },
  ],

  // Krok 2 — Parametry odběrného místa
  hasFveVte: 'yes',
  fveVtePower: '150',
  accumulationPercentage: '30',
  interestedInFveVte: '',
  interestedInInstallationProcessing: '',
  interestedInElectromobility: 'yes',
  hasTransformer: 'yes',
  transformerPower: '630',
  transformerVoltage: '22',
  coolingType: 'oil',
  transformerYear: '2018',
  transformerType: 'ABB RESIBLOC',
  transformerCurrent: '16',
  circuitBreakerType: '',
  customCircuitBreaker: '',
  sharesElectricity: 'no',
  electricityShared: '',
  receivesSharedElectricity: 'no',
  electricityReceived: '',
  mainCircuitBreaker: '250',
  reservedPower: '200',
  reservedOutput: '180',
  monthlyConsumption: '45',
  monthlyMaxConsumption: '120',
  significantConsumption: 'Výrobní linka pracuje v třísměnném provozu, špičky v ranních hodinách.',

  // Krok 3 — Energetické potřeby
  hasDistributionCurves: 'no',
  distributionTerritory: 'pre',
  ldsName: '',
  ldsOwner: '',
  ldsNotes: '',
  measurementType: 'quarter-hour',
  measurementTypeOther: '',
  yearlyConsumption: '540',
  dailyAverageConsumption: '1480',
  maxConsumption: '180',
  minConsumption: '25',
  hasCriticalConsumption: 'yes',
  criticalConsumptionDescription: 'Serverovna a chladicí systém musí běžet nepřetržitě.',
  energyAccumulation: 'specific',
  energyAccumulationAmount: '500',
  batteryCycles: 'multiple',
  requiresBackup: 'yes',
  backupDescription: 'Záložní napájení pro serverovnu a bezpečnostní systémy.',
  backupDuration: 'hours-1-3',
  backupDurationHours: '',
  priceOptimization: 'yes',
  hasElectricityProblems: 'yes',
  electricityProblemsDetails: 'Občasné výpadky napětí – přibližně 2× měsíčně.',
  hasEnergyAudit: 'no',
  energyAuditDetails: '',
  hasOwnEnergySource: 'yes',
  ownEnergySourceDetails: 'FVE 150 kWp na střeše výrobní haly.',

  // TimeSlider — vzory spotřeby
  weekdayPattern: {
    morningPeakStart: 6,
    morningPeakEnd: 10,
    morningPeakConsumption: 85,
    noonLowStart: 11,
    noonLowEnd: 13,
    noonLowConsumption: 50,
    afternoonPeakStart: 14,
    afternoonPeakEnd: 18,
    afternoonPeakConsumption: 90,
    nightLowStart: 22,
    nightLowEnd: 5,
    nightLowConsumption: 20,
    q1Consumption: 80,
    q2Consumption: 70,
    q3Consumption: 75,
    q4Consumption: 85,
  },
  weekendPattern: {
    morningPeakStart: 8,
    morningPeakEnd: 12,
    morningPeakConsumption: 40,
    noonLowStart: 12,
    noonLowEnd: 14,
    noonLowConsumption: 30,
    afternoonPeakStart: 14,
    afternoonPeakEnd: 17,
    afternoonPeakConsumption: 45,
    nightLowStart: 21,
    nightLowEnd: 7,
    nightLowConsumption: 15,
    q1Consumption: 35,
    q2Consumption: 30,
    q3Consumption: 32,
    q4Consumption: 38,
  },

  // Krok 4 — Cíle a očekávání
  goals: {
    fveOverflow: true,
    peakShaving: true,
    backupPower: true,
    machineSupport: false,
    powerReduction: true,
    energyTrading: false,
    subsidy: true,
    other: false,
  },
  otherPurposeDescription: '',
  goalDetails: 'Primárně chceme optimalizovat spotřebu z FVE a snížit špičky odběru ze sítě.',
  priority1: 'fve-overflow',
  priority2: 'peak-shaving',
  priority3: 'backup-power',

  // Krok 5 — Infrastruktura a prostor
  siteDescription: 'Areál se dvěma výrobními halami a administrativní budovou. K dispozici zpevněná plocha u trafostanice.',
  hasOutdoorSpace: 'yes',
  outdoorSpaceSize: '80',
  hasIndoorSpace: 'yes',
  indoorSpaceType: 'Nevyužitá technická místnost v přízemí haly B',
  indoorSpaceSize: '35',
  accessibility: 'limited',
  accessibilityLimitations: 'Příjezd kamionem možný pouze přes hlavní bránu, nutné ohlášení 24 h předem.',
  hasProjectDocumentation: 'no',
  documentationTypes: {
    sitePlan: false,
    electricalPlan: false,
    buildingPlan: false,
    other: false,
  },
  infrastructureNotes: 'Trafostanice je umístěna na severní straně areálu, cca 15 m od navrhované lokace baterie.',

  // Krok 6 — Provozní a legislativní rámec
  gridConnectionPlanned: 'no',
  powerIncreaseRequested: 'no',
  requestedPowerIncrease: '',
  requestedOutputIncrease: '',
  connectionApplicationBy: 'customerbyelectree',
  willingToSignPowerOfAttorney: 'yes',
  hasEnergeticSpecialist: 'yes',
  specialistName: 'Ing. Petr Svoboda',
  specialistPosition: 'specialist',
  specialistPhone: '+420 603 987 654',
  specialistEmail: 'svoboda@energo-consulting.cz',
  legislativeNotes: 'Firma má platné stavební povolení pro technologické změny v areálu.',

  // Krok 7 — Navržený postup a poznámky
  proposedSteps: {
    preliminary: true,
    technical: true,
    detailed: false,
    consultancy: true,
    support: false,
    other: false,
    otherDescription: '',
  },
  additionalNotes: 'Preferujeme realizaci v Q2 2026. Rozpočet předběžně 8–12 mil. Kč.',
  agreements: {
    dataProcessing: true,
    technicalVisit: true,
    marketing: false,
  },

  // Krok 8 — Energetický dotazník
  billingMethod: 'gradual',
  spotSurcharge: '',
  fixPrice: '',
  fixPercentage: '60',
  spotPercentage: '40',
  gradualFixPrice: '3.20',
  gradualSpotSurcharge: '0.15',
  currentEnergyPrice: '4.50',
  priceImportance: 7,
  electricitySharing: 'no',
  sharingDetails: '',
  hasGas: 'yes',
  gasConsumption: '12000',
  gasBill: '180000',
  gasUsage: {
    heating: true,
    hotWater: true,
    technology: true,
    cooking: false,
  },
  hotWaterConsumption: '800',
  steamConsumption: '120',
  otherConsumption: 'Kompresorová stanice pro výrobní linku.',
  hasCogeneration: 'no',
  cogenerationDetails: '',
  energyNotes: 'Uvažujeme o přechodu z plynového vytápění na tepelná čerpadla v horizontu 2–3 let.',
})
